# Generated by Django 4.2.18 on 2025-02-16 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipv4_address', models.TextField(default='192.168.0.254')),
                ('gateway_address', models.TextField(default='192.168.0.1')),
            ],
        ),
    ]
