# Generated by Django 4.2.18 on 2025-03-04 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpgsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='networksettings',
            name='ap_password',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='networksettings',
            name='ap_ssid',
            field=models.TextField(default=''),
        ),
    ]
