# Generated by Django 4.2.18 on 2025-03-04 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpgsapp', '0002_networksettings_ap_password_networksettings_ap_ssid'),
    ]

    operations = [
        migrations.AddField(
            model_name='networksettings',
            name='host_name',
            field=models.TextField(default='cpgs'),
        ),
        migrations.AddField(
            model_name='networksettings',
            name='server_ip',
            field=models.TextField(default='192.168.1.100'),
        ),
        migrations.AddField(
            model_name='networksettings',
            name='server_port',
            field=models.TextField(default='9090'),
        ),
        migrations.AddField(
            model_name='networksettings',
            name='subnet_mask',
            field=models.TextField(default='255.255.255.1'),
        ),
        migrations.AlterField(
            model_name='networksettings',
            name='ap_password',
            field=models.TextField(default='admin@1234'),
        ),
        migrations.AlterField(
            model_name='networksettings',
            name='ap_ssid',
            field=models.TextField(default='admin'),
        ),
    ]
