# Generated by Django 4.2.18 on 2025-03-04 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpgsapp', '0003_networksettings_host_name_networksettings_server_ip_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='networksettings',
            name='ip_type',
            field=models.TextField(choices=[('static', 'static'), ('dynamic', 'dynamic')], default='static'),
        ),
    ]
