# Generated by Django 4.2.18 on 2025-03-10 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpgsapp', '0004_networksettings_ip_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='admin', max_length=100)),
                ('password', models.CharField(default='admin', max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='networksettings',
            name='ap_password',
            field=models.CharField(default='admin@1234', max_length=100),
        ),
        migrations.AlterField(
            model_name='networksettings',
            name='ap_ssid',
            field=models.CharField(default='admin', max_length=100),
        ),
        migrations.AlterField(
            model_name='networksettings',
            name='gateway_address',
            field=models.GenericIPAddressField(default='192.168.0.1'),
        ),
        migrations.AlterField(
            model_name='networksettings',
            name='host_name',
            field=models.CharField(default='cpgs', max_length=50),
        ),
        migrations.AlterField(
            model_name='networksettings',
            name='ip_type',
            field=models.CharField(choices=[('static', 'Static'), ('dynamic', 'Dynamic')], default='static', max_length=10),
        ),
        migrations.AlterField(
            model_name='networksettings',
            name='ipv4_address',
            field=models.GenericIPAddressField(default='192.168.0.254'),
        ),
        migrations.AlterField(
            model_name='networksettings',
            name='server_ip',
            field=models.GenericIPAddressField(default='192.168.1.100'),
        ),
        migrations.AlterField(
            model_name='networksettings',
            name='server_port',
            field=models.PositiveIntegerField(default=9090),
        ),
        migrations.AlterField(
            model_name='networksettings',
            name='subnet_mask',
            field=models.GenericIPAddressField(default='255.255.255.0'),
        ),
    ]
