# Generated by Django 4.2.18 on 2025-03-14 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpgsapp', '0005_account_alter_networksettings_ap_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='networksettings',
            name='default_ap_password',
            field=models.CharField(default='LiquidlabCPGS', max_length=100),
        ),
        migrations.AddField(
            model_name='networksettings',
            name='default_ap_ssid',
            field=models.CharField(default='LiquidlabCPGSDefaultSSID', max_length=100),
        ),
    ]
